// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jntohdhqyauqtirmpqmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudG9oZGhxeWF1cXRpcm1wcW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzIwNTMsImV4cCI6MjA3Mjg0ODA1M30.pA8mX0Mw5TygmMnockAqtZQkl-Gxv6Q6AwHFsiFZXeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});